#ifndef LIBTRITON_CORE_DIALECT_TVMFFI_IR_TVMFFIDIALECT_H_
#define LIBTRITON_CORE_DIALECT_TVMFFI_IR_TVMFFIDIALECT_H_

#include "mlir/IR/Dialect.h"

#include "libtriton-core/Dialect/TVMFFI/IR/TVMFFIDialect.h.inc"

#endif // LIBTRITON_CORE_DIALECT_TVMFFI_IR_TVMFFIDIALECT_H_
