// RUN: libtriton-core-opt %s -emit-tvm-ffi-interface -convert-to-llvm -reconcile-unrealized-casts | mlir-opt -convert-arith-to-llvm -convert-func-to-llvm -reconcile-unrealized-casts | mlir-translate --mlir-to-llvmir -o %t.ll
// RUN: llc -filetype=obj %t.ll -o %t.o
// RUN: clang -shared -fPIC -fsanitize=address %t.o -o %t_asan%shlibext -lm
// RUN: env ASAN_OPTIONS=detect_leaks=1:halt_on_error=1:abort_on_error=1 %e2e-dlpack-runner-asan %t_asan%shlibext scalar_add_kernel

// Minimal CPU scalar e2e test: scalar_add_kernel(x, y) -> x + y.
// Uses TVM FFI stable C ABI wrappers generated by emit-tvm-ffi-interface.

func.func @scalar_add_kernel(%x: i64, %y: i64) -> i64
  attributes {
    tvm_ffi.emit_tvm_ffi_interface
  }
{
  %sum = arith.addi %x, %y : i64
  return %sum : i64
}
