//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.

// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_CORE_DIALECT_TVMFFI_IR_TVMFFI_TD_
#define TRIDENT_CORE_DIALECT_TVMFFI_IR_TVMFFI_TD_

include "mlir/IR/OpBase.td"

include "trident-core/Dialect/TVMFFI/IR/TVMFFIBase.td"
include "trident-core/Dialect/TVMFFI/IR/TVMFFIAttributes.td"
include "trident-core/Dialect/TVMFFI/IR/TVMFFIOps.td"

#endif // TRIDENT_CORE_DIALECT_TVMFFI_IR_TVMFFI_TD_
