//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_CORE_DIALECT_ARITHEXT_IR_ARITHEXT_TD_
#define TRIDENT_CORE_DIALECT_ARITHEXT_IR_ARITHEXT_TD_

include "mlir/IR/OpBase.td"

include "trident/core/Dialect/ArithExt/IR/ArithExtBase.td"
include "trident/core/Dialect/ArithExt/IR/ArithExtOps.td"

#endif // TRIDENT_CORE_DIALECT_ARITHEXT_IR_ARITHEXT_TD_
