add_subdirectory(ArithExtToScf)
add_subdirectory(DecomposeTVMFFI)
add_subdirectory(GeneralizeAtenOps)
add_subdirectory(Pipeline)
add_subdirectory(TorchExtToGPU)
add_subdirectory(TorchToCf)
add_subdirectory(TorchToTVMFFI)
add_subdirectory(TVMFFIToFunc)
add_subdirectory(TVMFFIToLLVM)
add_subdirectory(Utils)
