// RUN: libtriton-core-opt %s --torch-to-llvm-pipeline | FileCheck %s
// RUN: libtriton-core-opt %s --torch-to-llvm-pipeline | mlir-translate --mlir-to-llvmir
//
// This test verifies that the TorchToLLVM pipeline correctly lowers
// torch.aten.empty_like (with torch.constant.bool) all the way to LLVM
// dialect, and that a tvm_ffi.func wrapper calling the original
// func.func via func.call is also correctly lowered.
//
// The wrapper pattern: tvm_ffi.func unpacks a !torch.tensor from the TVM FFI
// args array, calls the lowered llvm.func @torch.aten.empty_like, then packs
// the result back into the ret slot.

// TVM FFI runtime declarations (generated by ConvertTVMFFIToLLVM):
// CHECK:       llvm.func @mLibTritonPackTensorToTVMFFIAny(!llvm.ptr, !llvm.ptr) -> i32
// CHECK:       llvm.func @TVMFFIErrorSetRaisedFromCStr(!llvm.ptr, !llvm.ptr)
// CHECK:       llvm.func @mLibTritonUnpackTVMFFIAnyToTensor(!llvm.ptr, !llvm.ptr) -> i32

// AOTInductor globals + dispatcher (generated by rewrite-torch-as-aoti):
// CHECK:       llvm.mlir.global internal constant @__libtriton_constant_overload_
// CHECK:       llvm.mlir.global internal constant @"__libtriton_constant_op_aten::empty_like"
// CHECK:       llvm.func @aoti_torch_call_dispatcher
// CHECK-SAME:    (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32

// -- func.func @torch.aten.empty_like lowered to llvm.func --
// CHECK-LABEL: llvm.func @torch.aten.empty_like(
// CHECK-SAME:    %[[ARG0:.*]]: !llvm.ptr) -> !llvm.ptr {
// CHECK-NOT:     arith.constant
// CHECK-NOT:     torch_c.from_i1
// CHECK:         %[[OVERLOAD:.*]] = llvm.mlir.addressof @__libtriton_constant_overload_
// CHECK-SAME:      : !llvm.ptr
// CHECK:         %[[OPNAME:.*]] = llvm.mlir.addressof @"__libtriton_constant_op_aten::empty_like"
// CHECK-SAME:      : !llvm.ptr
// CHECK:         %[[C0:.*]] = llvm.mlir.constant(0 : i64) : i64
// CHECK:         %[[C6:.*]] = llvm.mlir.constant(6 : i64) : i64
// CHECK-NEXT:    %[[SLOTS:.*]] = llvm.alloca %[[C6]] x i64 : (i64) -> !llvm.ptr
// Store the input tensor pointer at slot[0].
// CHECK:         %[[PTRINT:.*]] = llvm.ptrtoint %[[ARG0]] : !llvm.ptr to i64
// CHECK-NEXT:    llvm.store %[[PTRINT]], %[[SLOTS]] : i64, !llvm.ptr
// Store zero (lowered from torch.constant.none / torch.constant.bool false)
// at slots[1..5] for the 5 trailing none/bool arguments of empty_like.
// CHECK:         %[[GEP1:.*]] = llvm.getelementptr %[[SLOTS]][1]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP1]] : i64, !llvm.ptr
// CHECK:         %[[GEP2:.*]] = llvm.getelementptr %[[SLOTS]][2]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP2]] : i64, !llvm.ptr
// CHECK:         %[[GEP3:.*]] = llvm.getelementptr %[[SLOTS]][3]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP3]] : i64, !llvm.ptr
// CHECK:         %[[GEP4:.*]] = llvm.getelementptr %[[SLOTS]][4]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP4]] : i64, !llvm.ptr
// CHECK:         %[[GEP5:.*]] = llvm.getelementptr %[[SLOTS]][5]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP5]] : i64, !llvm.ptr
// Call dispatcher with (op_name, overload_name, slot_array).
// CHECK:         %[[RET:.*]] = llvm.call @aoti_torch_call_dispatcher(%[[OPNAME]], %[[OVERLOAD]], %[[SLOTS]])
// CHECK-SAME:      : (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32
// Load the result tensor handle from slot[0] (the extra return slot).
// CHECK-NEXT:    %[[RES_VAL:.*]] = llvm.load %[[SLOTS]] : !llvm.ptr -> i64
// CHECK-NEXT:    %[[RES_PTR:.*]] = llvm.inttoptr %[[RES_VAL]] : i64 to !llvm.ptr
// CHECK-NEXT:    llvm.return %[[RES_PTR]] : !llvm.ptr
func.func @torch.aten.empty_like(%arg0: !torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64> {
  %none = torch.constant.none
  %false = torch.constant.bool false
  %0 = torch.aten.empty_like %arg0, %none, %none, %none, %false, %none : !torch.vtensor<[200,200,26],f64>, !torch.none, !torch.none, !torch.none, !torch.bool, !torch.none -> !torch.vtensor<[200,200,26],f64>
  return %0 : !torch.vtensor<[200,200,26],f64>
}

// tvm_ffi.func wrapper: calls func.func @torch.aten.empty_like via func.call.
// Uses the same !torch.vtensor type so the call signature matches directly.
// CHECK-LABEL: llvm.func @__tvm_ffi_empty_like(
// CHECK-SAME:    %arg0: !llvm.ptr, %[[WRAP_ARGS:.*]]: !llvm.ptr, %arg2: i32, %[[WRAP_RET:.*]]: !llvm.ptr) -> i32 {
// CHECK:         %[[UNPACK_OK:.*]] = llvm.call @mLibTritonUnpackTVMFFIAnyToTensor(%[[WRAP_ARGS]], %{{.*}})
// CHECK:         %[[HANDLE:.*]] = llvm.load %{{.*}} : !llvm.ptr -> !llvm.ptr
// CHECK:         %[[CALLEE_RET:.*]] = llvm.call @torch.aten.empty_like(%[[HANDLE]])
// CHECK-SAME:      : (!llvm.ptr) -> !llvm.ptr
// CHECK:         llvm.call @mLibTritonPackTensorToTVMFFIAny(%[[CALLEE_RET]], %[[WRAP_RET]])
// CHECK:         llvm.return %{{.*}} : i32

tvm_ffi.func @empty_like(%arg0: !torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64> {
  %0 = func.call @torch.aten.empty_like(%arg0) : (!torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64>
  tvm_ffi.return %0 : !torch.vtensor<[200,200,26],f64>
}
