// RUN: libtriton-core-opt %s --torch-to-llvm-pipeline | FileCheck %s
// RUN: libtriton-core-opt %s --torch-to-llvm-pipeline | mlir-translate --mlir-to-llvmir
//
// This test verifies that the TorchToLLVM pipeline correctly lowers
// torch.aten.empty_like (with torch.constant.bool) all the way to LLVM
// dialect, and that a tvm_ffi.func wrapper calling the original
// func.func via func.call is also correctly lowered.
//
// The wrapper pattern: tvm_ffi.func unpacks a !torch.tensor from the TVM FFI
// args array, calls the lowered llvm.func @torch.aten.empty_like, then packs
// the result back into the ret slot.

// TVM FFI runtime declarations (generated by ConvertTVMFFIToLLVM):
// CHECK:       llvm.func @mLibTritonTensorToTVMFFIObject(!llvm.ptr, !llvm.ptr) -> i32

// TorchExt globals + dispatcher (generated by TorchExtToLLVM):
// CHECK:       llvm.mlir.global internal constant @__libtriton_constant_overload_
// CHECK:       llvm.mlir.global internal constant @"__libtriton_constant_op_aten::empty_like"
// CHECK:       llvm.func @aoti_torch_call_dispatcher
// CHECK-SAME:    (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32

// mLibTritonTVMFFIObjectToTensor is referenced by the dispatcher call
// (TorchExtToLLVM converts TVMFFIObjectHandle → AtenTensorHandle):
// CHECK:       llvm.func @mLibTritonTVMFFIObjectToTensor(!llvm.ptr, !llvm.ptr) -> i32

// -- func.func @torch.aten.empty_like lowered to llvm.func --
// CHECK-LABEL: llvm.func @torch.aten.empty_like(
// CHECK-SAME:    %[[ARG0:.*]]: !llvm.ptr) -> !llvm.ptr {
// CHECK:         %[[OVERLOAD:.*]] = llvm.mlir.addressof @__libtriton_constant_overload_
// CHECK-SAME:      : !llvm.ptr
// CHECK:         %[[OPNAME:.*]] = llvm.mlir.addressof @"__libtriton_constant_op_aten::empty_like"
// CHECK-SAME:      : !llvm.ptr
// Constants may appear in any order.
// CHECK-DAG:     %[[C0:.*]] = llvm.mlir.constant(0 : i64) : i64
// CHECK-DAG:     %[[C1:.*]] = llvm.mlir.constant(1 : i64) : i64
// CHECK-DAG:     %[[C6:.*]] = llvm.mlir.constant(6 : i64) : i64
// CHECK:         %[[SLOTS:.*]] = llvm.alloca %[[C6]] x i64 : (i64) -> !llvm.ptr
// Unpack TVMFFIObjectHandle → AtenTensorHandle before passing to dispatcher.
// CHECK:         llvm.alloca %[[C1]] x !llvm.ptr
// CHECK:         llvm.call @mLibTritonTVMFFIObjectToTensor(%[[ARG0]],
// CHECK:         llvm.load {{%.*}} : !llvm.ptr -> !llvm.ptr
// Store the input tensor pointer at slot[0].
// CHECK:         %[[PTRINT:.*]] = llvm.ptrtoint {{%.*}} : !llvm.ptr to i64
// CHECK-NEXT:    llvm.store %[[PTRINT]], %[[SLOTS]] : i64, !llvm.ptr
// Store zero (lowered from torch.constant.none / torch.constant.bool false)
// at slots[1..5] for the 5 trailing none/bool arguments of empty_like.
// CHECK:         %[[GEP1:.*]] = llvm.getelementptr %[[SLOTS]][1]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP1]] : i64, !llvm.ptr
// CHECK:         %[[GEP2:.*]] = llvm.getelementptr %[[SLOTS]][2]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP2]] : i64, !llvm.ptr
// CHECK:         %[[GEP3:.*]] = llvm.getelementptr %[[SLOTS]][3]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP3]] : i64, !llvm.ptr
// CHECK:         %[[GEP4:.*]] = llvm.getelementptr %[[SLOTS]][4]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP4]] : i64, !llvm.ptr
// CHECK:         %[[GEP5:.*]] = llvm.getelementptr %[[SLOTS]][5]
// CHECK-NEXT:    llvm.store %[[C0]], %[[GEP5]] : i64, !llvm.ptr
// Call dispatcher with (op_name, overload_name, slot_array).
// CHECK:         %[[RET:.*]] = llvm.call @aoti_torch_call_dispatcher(%[[OPNAME]], %[[OVERLOAD]], %[[SLOTS]])
// CHECK-SAME:      : (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32
// Load the result tensor handle from slot[0], then pack back to TVMFFIObjectHandle.
// CHECK-NEXT:    %[[RES_VAL:.*]] = llvm.load %[[SLOTS]] : !llvm.ptr -> i64
// CHECK-NEXT:    %[[RES_PTR:.*]] = llvm.inttoptr %[[RES_VAL]] : i64 to !llvm.ptr
// Pack the AtenTensorHandle back into a TVMFFIObjectHandle for the caller.
// CHECK:         llvm.alloca %[[C1]] x !llvm.ptr
// CHECK:         llvm.call @mLibTritonTensorToTVMFFIObject(%[[RES_PTR]],
// CHECK:         llvm.load {{%.*}} : !llvm.ptr -> !llvm.ptr
// CHECK-NEXT:    llvm.return {{%.*}} : !llvm.ptr
func.func @torch.aten.empty_like(%arg0: !torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64> {
  %none = torch.constant.none
  %false = torch.constant.bool false
  %0 = torch.aten.empty_like %arg0, %none, %none, %none, %false, %none : !torch.vtensor<[200,200,26],f64>, !torch.none, !torch.none, !torch.none, !torch.bool, !torch.none -> !torch.vtensor<[200,200,26],f64>
  return %0 : !torch.vtensor<[200,200,26],f64>
}

// tvm_ffi.func wrapper: calls func.func @torch.aten.empty_like via func.call.
// CHECK-LABEL: llvm.func @__tvm_ffi_empty_like(
// CHECK-SAME:    %arg0: !llvm.ptr, %[[WRAP_ARGS:.*]]: !llvm.ptr, %arg2: i32, %[[WRAP_RET:.*]]: !llvm.ptr) -> i32 {
// Entry block: extract TVMFFIObjectHandle from TVMFFIAny arg,
// then wrap result into TVMFFIAny struct before storing to retPtr.
// CHECK:         %[[ZERO:.*]] = llvm.mlir.constant(0 : i32) : i32
// CHECK:         %[[TYPE70:.*]] = llvm.mlir.constant(70 : i32) : i32
// CHECK:         %[[UNDEF:.*]] = llvm.mlir.undef : !llvm.struct<(i32, i32, i64)>
// CHECK:         %[[VOBJ_GEP:.*]] = llvm.getelementptr %[[WRAP_ARGS]][0, 2]
// CHECK:         %[[VOBJ_I64:.*]] = llvm.load %[[VOBJ_GEP]]
// CHECK:         %[[ARG_HANDLE:.*]] = llvm.inttoptr %[[VOBJ_I64]]
// CHECK:         llvm.br
// Body block: call the lowered function.
// CHECK:         %[[CALLEE_RET:.*]] = llvm.call @torch.aten.empty_like(%[[ARG_HANDLE]])
// CHECK-SAME:      : (!llvm.ptr) -> !llvm.ptr
// Wrap the returned handle directly into TVMFFIAny:
// CHECK:         %[[WITH_IDX:.*]] = llvm.insertvalue %[[TYPE70]], %[[UNDEF]][0]
// CHECK:         %[[VOBJ:.*]] = llvm.ptrtoint %[[CALLEE_RET]]
// CHECK:         %[[WRAPPED:.*]] = llvm.insertvalue %[[VOBJ]], %[[WITH_IDX]][2]
// CHECK:         llvm.store %[[WRAPPED]], %[[WRAP_RET]]
// CHECK:         llvm.return %[[ZERO]] : i32

tvm_ffi.func @empty_like(%arg0: !torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64> {
  %0 = func.call @torch.aten.empty_like(%arg0) : (!torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64>
  tvm_ffi.return %0 : !torch.vtensor<[200,200,26],f64>
}
