//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_CORE_PYTHON_DIALECTS_TORCHEXTOPSPYBIND_TD_
#define TRIDENT_CORE_PYTHON_DIALECTS_TORCHEXTOPSPYBIND_TD_

include "trident/core/Dialect/TorchExt/IR/TorchExtOps.td"

#endif // TRIDENT_CORE_PYTHON_DIALECTS_TORCHEXTOPSPYBIND_TD_
