//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_PYTHON_BINDINGS_TORCH_CONVERSION_OPS
#define TRIDENT_PYTHON_BINDINGS_TORCH_CONVERSION_OPS

include "torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td"

#endif // TRIDENT_PYTHON_BINDINGS_TORCH_CONVERSION_OPS
