//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.

// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_CORE_PYTHON_DIALECTS_TVMFFIOPSPYBIND_TD_
#define TRIDENT_CORE_PYTHON_DIALECTS_TVMFFIOPSPYBIND_TD_

include "trident/core/Dialect/TVMFFI/IR/TVMFFIOps.td"

#endif // TRIDENT_CORE_PYTHON_DIALECTS_TVMFFIOPSPYBIND_TD_
