//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_CORE_DIALECT_TORCHEXT_IR_TORCHEXT_TD_
#define TRIDENT_CORE_DIALECT_TORCHEXT_IR_TORCHEXT_TD_

include "mlir/IR/OpBase.td"

include "trident-core/Dialect/TorchExt/IR/TorchExtBase.td"
include "trident-core/Dialect/TorchExt/IR/TorchExtOps.td"

#endif // TRIDENT_CORE_DIALECT_TORCHEXT_IR_TORCHEXT_TD_
