//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

// RUN: trident-core-opt %s --torch-to-llvm-pipeline | FileCheck %s
//
// This test verifies that the TorchToLLVM pipeline correctly lowers
// torch.aten.empty.memory_format with externally-provided shape (!torch.list<int>),
// dtype (!torch.int), and device (!torch.Device) parameters, all the way to LLVM
// dialect, and that a tvm_ffi.func wrapper unpacking these from TVM FFI args is
// also correctly lowered.
//
// The wrapper pattern: tvm_ffi.func unpacks shape (as TVMFFIArray), device
// (as kTVMFFIDevice=6), and dtype (as kTVMFFIInt=1) from the FFI arg slots,
// calls the lowered llvm.func @torch.aten.empty.memory_format, then packs
// the result (kTVMFFITensor=70) back into the ret slot.

// TorchExt globals + dispatcher (generated by TorchExtToLLVM):
// CHECK:       llvm.func @TVMFFIObjectIncRef(!llvm.ptr) -> i32
// CHECK:       llvm.mlir.global internal constant @__trident_constant_overload_
// CHECK:       llvm.mlir.global internal constant @"__trident_constant_op_aten::empty"
// CHECK:       llvm.func @aoti_torch_call_dispatcher
// CHECK-SAME:    (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32

// -- func.func @torch.aten.empty.memory_format lowered to llvm.func --
// CHECK-LABEL: llvm.func @torch.aten.empty.memory_format(
// CHECK-SAME:    %[[SHAPE:.*]]: !llvm.struct<(i32, i32, i64)>, %[[DTYPE:.*]]: !llvm.struct<(i32, i32, i64)>, %[[DEVICE:.*]]: !llvm.struct<(i32, i32, i64)>) -> !llvm.struct<(i32, i32, i64)> {
// CHECK:         %[[OPNAME:.*]] = llvm.mlir.addressof @"__trident_constant_op_aten::empty"
// CHECK-SAME:      : !llvm.ptr
// Allocate the dispatcher slot array early.
// CHECK:         %[[SLOTS:.*]] = llvm.alloca {{%.*}} x i64 : (i64) -> !llvm.ptr
// Extract shape payload from TVMFFIAny arg[2].
// CHECK:         llvm.extractvalue %[[SHAPE]][2] : !llvm.struct<(i32, i32, i64)>
// ffi.ArraySize: TVMFFIFunctionGetGlobal + Call + DecRef.
// CHECK:         llvm.call @TVMFFIFunctionGetGlobal
// CHECK:         llvm.call @TVMFFIFunctionCall
// CHECK:         llvm.call @TVMFFIObjectDecRef
// torch_new_list_reserve_size.
// CHECK:         llvm.call @torch_new_list_reserve_size
// Loop header with block argument (i counter).
// CHECK:         llvm.br ^bb{{.*}}({{%.*}} : i64)
// Loop: cond_br with i counter passed via block args.
// CHECK:         llvm.cond_br {{%.*}}, ^bb{{.*}}, ^bb{{.*}}
// Loop body: ffi.ArrayGetItem via GetGlobal + Call + DecRef.
// CHECK:         llvm.call @TVMFFIFunctionGetGlobal
// CHECK:         llvm.call @TVMFFIFunctionCall
// CHECK:         llvm.call @TVMFFIObjectDecRef
// torch_list_push_back.
// CHECK:         llvm.call @torch_list_push_back
// Store list result at slot 0, dtype at slot 1, device at slot 2, none at slots 3-5.
// CHECK:         llvm.store {{%.*}}, %[[SLOTS]] : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][1]
// CHECK:         llvm.getelementptr %[[SLOTS]][5]
// Call dispatcher.
// CHECK:         llvm.call @aoti_torch_call_dispatcher(%[[OPNAME]], {{%.*}}, %[[SLOTS]])
// CHECK:         %[[RES_VAL:.*]] = llvm.load %[[SLOTS]] : !llvm.ptr -> i64
// CHECK:         %[[ATEN_PTR:.*]] = llvm.inttoptr %[[RES_VAL]] : i64 to !llvm.ptr
// CHECK:         llvm.call @mTridentTensorToTVMFFIObject(%[[ATEN_PTR]],
// CHECK:         %[[RES_PTR:.*]] = llvm.load {{%.*}} : !llvm.ptr -> !llvm.ptr
// Pack result into TVMFFIAny and return.
// CHECK:         llvm.insertvalue {{%.*}}, {{%.*}}[0] : !llvm.struct<(i32, i32, i64)>
// CHECK:         llvm.insertvalue {{%.*}}, {{%.*}}[2] : !llvm.struct<(i32, i32, i64)>
// ObjectIncRef + ObjectDecRef for the returned tensor (ownership transfer).
// CHECK:         llvm.call @TVMFFIObjectIncRef
// CHECK:         llvm.call @TVMFFIObjectDecRef
// CHECK-NEXT:    llvm.return {{%.*}} : !llvm.struct<(i32, i32, i64)>
func.func @torch.aten.empty.memory_format(%shape: !torch.list<int>, %dtype: !torch.int, %device: !torch.Device) -> !torch.vtensor<[?,?],f64> {
  %none = torch.constant.none
  %layout = torch.constant.int 0
  %0 = torch.aten.empty.memory_format %shape, %dtype, %layout, %device, %none, %none : !torch.list<int>, !torch.int, !torch.int, !torch.Device, !torch.none, !torch.none -> !torch.vtensor<[?,?],f64>
  return %0 : !torch.vtensor<[?,?],f64>
}

// tvm_ffi.func wrapper: unpacks shape, device, and dtype from TVM FFI args.
// CHECK-LABEL: llvm.func @__tvm_ffi_empty(
// CHECK-SAME:    %arg0: !llvm.ptr, %[[ARGS:.*]]: !llvm.ptr, %arg2: i32, %[[RET:.*]]: !llvm.ptr) -> i32 {
// Unpack shape, device, dtype directly as TVMFFIAny structs (uniform lowering).
// CHECK:         %[[ZERO:.*]] = llvm.mlir.constant(0 : i32) : i32
// CHECK:         %[[SHAPE_LOAD:.*]] = llvm.load %[[ARGS]] : !llvm.ptr -> !llvm.struct<(i32, i32, i64)>
// CHECK:         %[[DEV_GEP:.*]] = llvm.getelementptr %[[ARGS]][1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i32, i64)>
// CHECK:         %[[DEV_LOAD:.*]] = llvm.load %[[DEV_GEP]] : !llvm.ptr -> !llvm.struct<(i32, i32, i64)>
// CHECK:         %[[DTYPE_GEP:.*]] = llvm.getelementptr %[[ARGS]][2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i32, i64)>
// CHECK:         %[[DTYPE_LOAD:.*]] = llvm.load %[[DTYPE_GEP]] : !llvm.ptr -> !llvm.struct<(i32, i32, i64)>
// CHECK:         llvm.br
// Body block: cast args to TVMFFIAny, call the lowered function.
// CHECK:         %[[CALLEE_RET:.*]] = llvm.call @torch.aten.empty.memory_format({{%.*}}, {{%.*}}, {{%.*}}) : (!llvm.struct<(i32, i32, i64)>, !llvm.struct<(i32, i32, i64)>, !llvm.struct<(i32, i32, i64)>) -> !llvm.struct<(i32, i32, i64)>
// Store result TVMFFIAny directly to retPtr.
// CHECK:         llvm.store %[[CALLEE_RET]], %[[RET]]
// CHECK:         llvm.return %[[ZERO]] : i32

tvm_ffi.func @empty(%shape: !torch.list<int>, %device: !torch.Device, %dtype: !torch.int) -> !torch.tensor {
  %0 = func.call @torch.aten.empty.memory_format(%shape, %dtype, %device) : (!torch.list<int>, !torch.int, !torch.Device) -> !torch.vtensor<[?,?],f64>
  tvm_ffi.return %0 : !torch.vtensor<[?,?],f64>
}
