//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the MIT License.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

// RUN: trident-core-opt %s --torch-to-llvm-pipeline | FileCheck %s
//
// This test verifies that the TorchToLLVM pipeline correctly lowers
// torch.aten.empty_like (with torch.constant.bool) all the way to LLVM
// dialect, and that a tvm_ffi.func wrapper calling the original
// func.func via func.call is also correctly lowered.
//
// The wrapper pattern: tvm_ffi.func unpacks a !torch.tensor from the TVM FFI
// args array, calls the lowered llvm.func @torch.aten.empty_like, then packs
// the result back into the ret slot.

// TorchExt globals + dispatcher (generated by TorchExtToLLVM):
// CHECK:       llvm.func @TVMFFIObjectIncRef(!llvm.ptr) -> i32
// CHECK:       llvm.mlir.global internal constant @__trident_constant_overload_
// CHECK:       llvm.mlir.global internal constant @"__trident_constant_op_aten::empty_like"
// CHECK:       llvm.func @aoti_torch_call_dispatcher
// CHECK-SAME:    (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32

// -- func.func @torch.aten.empty_like lowered to llvm.func --
// CHECK-LABEL: llvm.func @torch.aten.empty_like(
// CHECK-SAME:    %[[ARG0:.*]]: !llvm.struct<(i32, i32, i64)>) -> !llvm.struct<(i32, i32, i64)> {
// CHECK:         %[[OPNAME:.*]] = llvm.mlir.addressof @"__trident_constant_op_aten::empty_like"
// CHECK-SAME:      : !llvm.ptr
// Constants may appear in any order.
// CHECK-DAG:     %[[C0:.*]] = llvm.mlir.constant(0 : i64) : i64
// CHECK-DAG:     %[[C6:.*]] = llvm.mlir.constant(6 : i64) : i64
// CHECK-DAG:     %[[C8:.*]] = llvm.mlir.constant(8 : i64) : i64
// Allocate the dispatcher slot array first.
// CHECK:         %[[SLOTS:.*]] = llvm.alloca %[[C6]] x i64 : (i64) -> !llvm.ptr
// Extract TVMFFIObjectHandle from TVMFFIAny arg[2].
// CHECK:         llvm.extractvalue %[[ARG0]][2] : !llvm.struct<(i32, i32, i64)>
// Convert TVMFFIObjectHandle -> AtenTensorHandle -> i64 via mTridentTVMFFIObjectToTensor, then store at slot[0].
// CHECK:         llvm.store {{%.*}}, %[[SLOTS]] : i64, !llvm.ptr
// Store zero at slots[1..5] for the 5 trailing none/bool arguments of empty_like.
// Each optional argument flows through a CondBr + merge block pattern;
// the slot array store is reached via a load from the merge's resultSlot.
// CHECK:         llvm.getelementptr %[[SLOTS]][1]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][2]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][3]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// Slot 4 (torch.constant.bool false → bool? pin_memory): box via malloc.
// CHECK:         llvm.call @malloc(%[[C8]]) : (i64) -> !llvm.ptr
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.ptrtoint {{%.*}} : !llvm.ptr to i64
// CHECK:         llvm.getelementptr %[[SLOTS]][4]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// Slot 5 (torch.none → optional memory_format): None → constant 0.
// CHECK:         llvm.getelementptr %[[SLOTS]][5]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// Call dispatcher with (op_name, overload_name, slot_array).
// CHECK:         %[[RET:.*]] = llvm.call @aoti_torch_call_dispatcher(%[[OPNAME]], {{%.*}}, %[[SLOTS]])
// CHECK-SAME:      : (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32
// Load the result from slot[0] and convert i64 → !llvm.ptr.
// CHECK-NEXT:    %[[RES_VAL:.*]] = llvm.load %[[SLOTS]] : !llvm.ptr -> i64
// CHECK-NEXT:    %[[ATEN_PTR:.*]] = llvm.inttoptr %[[RES_VAL]] : i64 to !llvm.ptr
// CHECK:         llvm.alloca {{%.*}} x !llvm.ptr : (i64) -> !llvm.ptr
// CHECK:         llvm.call @mTridentTensorToTVMFFIObject(%[[ATEN_PTR]],
// CHECK:         %[[RES_PTR:.*]] = llvm.load {{%.*}} : !llvm.ptr -> !llvm.ptr
// Pack into TVMFFIAny {kTVMFFITensor, 0, ptr} and return.
// CHECK:         llvm.insertvalue {{%.*}}, {{%.*}}[0] : !llvm.struct<(i32, i32, i64)>
// CHECK:         llvm.insertvalue {{%.*}}, {{%.*}}[2] : !llvm.struct<(i32, i32, i64)>
// ObjectIncRef + ObjectDecRef for the returned tensor (ownership transfer).
// CHECK:         llvm.call @TVMFFIObjectIncRef
// CHECK:         llvm.call @TVMFFIObjectDecRef
// CHECK-NEXT:    llvm.return {{%.*}} : !llvm.struct<(i32, i32, i64)>
func.func @torch.aten.empty_like(%arg0: !torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64> {
  %none = torch.constant.none
  %false = torch.constant.bool false
  %0 = torch.aten.empty_like %arg0, %none, %none, %none, %false, %none : !torch.vtensor<[200,200,26],f64>, !torch.none, !torch.none, !torch.none, !torch.bool, !torch.none -> !torch.vtensor<[200,200,26],f64>
  return %0 : !torch.vtensor<[200,200,26],f64>
}

// tvm_ffi.func wrapper: calls func.func @torch.aten.empty_like via func.call.
// CHECK-LABEL: llvm.func @__tvm_ffi_empty_like(
// CHECK-SAME:    %arg0: !llvm.ptr, %[[WRAP_ARGS:.*]]: !llvm.ptr, %arg2: i32, %[[WRAP_RET:.*]]: !llvm.ptr) -> i32 {
// Entry block: load TVMFFIAny arg directly (uniform lowering), then call.
// CHECK:         %[[ZERO:.*]] = llvm.mlir.constant(0 : i32) : i32
// CHECK:         %[[LOADED:.*]] = llvm.load %[[WRAP_ARGS]] : !llvm.ptr -> !llvm.struct<(i32, i32, i64)>
// CHECK:         llvm.br
// Body block: call the lowered function with TVMFFIAny arg.
// CHECK:         %[[CALLEE_RET:.*]] = llvm.call @torch.aten.empty_like({{%.*}}) : (!llvm.struct<(i32, i32, i64)>) -> !llvm.struct<(i32, i32, i64)>
// Store result TVMFFIAny directly to retPtr.
// CHECK:         llvm.store %[[CALLEE_RET]], %[[WRAP_RET]]
// CHECK:         llvm.return %[[ZERO]] : i32

tvm_ffi.func @empty_like(%arg0: !torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64> {
  %0 = func.call @torch.aten.empty_like(%arg0) : (!torch.vtensor<[200,200,26],f64>) -> !torch.vtensor<[200,200,26],f64>
  tvm_ffi.return %0 : !torch.vtensor<[200,200,26],f64>
}
