#ifndef LIBTRITON_CORE_C_DLPACKOPS_H
#define LIBTRITON_CORE_C_DLPACKOPS_H

#include "mlir-c/IR.h"
#include "mlir-c/Support.h"

#ifdef __cplusplus
extern "C" {
#endif

MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackFromMemRefOwnedOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackFromMemRefBorrowedOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackViewOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackToMemRefOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackNDimOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackShapeOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackStridesOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackByteOffsetOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDTypeOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDTypeCodeOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDTypeBitsOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDTypeLanesOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDeviceOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDeviceIdOp(MlirOperation operation);
MLIR_CAPI_EXPORTED bool
libtritonCoreOperationIsADLPackDeviceTypeOp(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackFromMemRefOwnedGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackFromMemRefOwnedGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackFromMemRefBorrowedGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackFromMemRefBorrowedGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackViewGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackViewGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackToMemRefGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackToMemRefGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackNDimGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackNDimGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackShapeGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackShapeGetIndex(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackShapeGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackStridesGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackStridesGetIndex(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackStridesGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackByteOffsetGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackByteOffsetGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeCodeGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeCodeGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeBitsGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeBitsGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeLanesGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDTypeLanesGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDeviceGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDeviceGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDeviceIdGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDeviceIdGetOutput(MlirOperation operation);

MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDeviceTypeGetInput(MlirOperation operation);
MLIR_CAPI_EXPORTED MlirValue
libtritonCoreDLPackDeviceTypeGetOutput(MlirOperation operation);

#ifdef __cplusplus
}
#endif

#endif // LIBTRITON_CORE_C_DLPACKOPS_H
