// RUN: libtriton-core-opt %s -emit-tvm-ffi-interface -convert-to-llvm -reconcile-unrealized-casts | mlir-opt -convert-arith-to-llvm -convert-func-to-llvm -reconcile-unrealized-casts | mlir-translate --mlir-to-llvmir -o %t.ll
// RUN: llc -filetype=obj %t.ll -o %t.o
// RUN: clang -shared -fPIC %t.o -o %t%shlibext -lm
// RUN: %e2e-dlpack-runner %t%shlibext add_kernel

// Minimal CPU e2e test: add_kernel(x, y) -> x + y.
// Uses TVM FFI stable C ABI wrappers generated by emit-tvm-ffi-interface.

func.func @add_kernel(%x: i64, %y: i64) -> i64
  attributes {
    tvm_ffi.emit_tvm_ffi_interface
  }
{
  %sum = arith.addi %x, %y : i64
  return %sum : i64
}
